version: '3'

services:
  react-app:
    build:
      context: ./Docker/react
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    ports:
      - "3000:3000"
    volumes:
      - ./build/react:/app
    environment:
      - NODE_ENV=development